### ISSUE TITLE
How to properly distribute for IIS

### ISSUE THREAD

**Issue by FMastro** [DanWahlin/Angular2-BareBones#2]
I'm sure this is an easy/silly question for those that already know.  I run "npm run bundle" and it creates a dist folder with the bundle.js file.  

How do I properly compile all the html, js and node references for transport up to a production server running IIS? 

If I point IIS to the src folder it can't find the node_modules. I don't want to move those in there and I don't want to point it to src as it has all the ts files. 

Is there some common way to export this bare bones to a dist folder with all needed files? Thanks.

**Comment by DanWahlin** [comment]
Currently the bundling only includes the Javascript so you'd still have to put the HTML templates on your IIS server to get it to run properly. Someday (if I get some free time) I'll try to bundle everything up. :-)
