### ISSUE TITLE
comparison of --minimal

### ISSUE THREAD

**Issue by pvssvikas** [DanWahlin/Angular2-BareBones#3]
Hello Dan,

Can you please help with a quick note of how this minimal project different from ng new <app-name> --minimal

Thanks,
-Vikas.

**Comment by DanWahlin** [comment]
They're very similar. This project came out way before the CLI was released as a demo for people new to Angular.

**Comment by pvssvikas** [comment]
Thanks a lot for clarifying, Dan.
